version: '3.8'

services:
  apiusuarios:
    build: .
        # context: .
        # dockerfile: Dockerfile
    ports:
       - "7267:7267"
    environment:
        ASPNETCORE_ENVIRONMENT: "Development"
        # ConnectionStrings__DefaultConnection=Server=db;Database=GestionUsuarios2;User Id=sa;Password=Admin123;
        # Redis__Configuration=redis:6379
        REDIS_CONNECTION_STRING: "redis:6379"
    depends_on:
       - db
       - redis
  
  apigateway:
    build:
        context: ../APIGateway
        dockerfile: Dockerfile
    ports:
        - "7115:7115"
    depends_on:
        - apiusuarios

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
        SA_PASSWORD: "Admin123"
        ACCEPT_EULA: "Y"
    ports:
        - "1433:1433"
    volumes :
        - sqlserver-data:/var/opt/mssql  
  redis:
    image: redis:latest
    ports:
        - "6379:6379"
volumes:
  sqlserver-data: